### ISSUE TITLE
Not able to mount the EFS file system using ansible with elevated privilege 

### ISSUE THREAD

**Issue by jblinuxclicks** [aws/efs-utils#3]
Description:
we installed efs utility and configured the EFS filesystem with EFS Mount points with in the VPC.
Added the entry in /etc/fstab for permanent mount like below.

`echo "mount fs-xxxxxxx /mnt/efs  efs tls,_netdev 0 0" >> /etc/fstab`
after this when i manually run the mount -a -t efs defaults  - it is working fine file system got mounted successfully without any issue.

But when i try to invoke the same thing from ansible mount module like below

```
- name: Mount up efs
  mount:
    path: /mnt/efs
    src: fs-xxxxxxxx
    fstype: efs
    opts: tls
    state: mounted
  become: true
  become_method: pbrun
  become_user: root
```

Note: Ansible is running as root privilaged user on the target host.

Expected Result:
EFS filesystem should get mounted without any issue.

Actual Result:
We are getting error in ansible saying like 
```
Error:
only root can run mount.efs

```
when i start debugging the issue i see the entry in __init__.py for efs
[https://github.com/aws/efs-utils/blob/555154b79572cd2a9f63782cac4c1062eb9b1ebd/src/mount_efs/__init__.py](url)

we are validating the user with getpass python module but some how even i am using the become in the ansible it is not help me to get ride of this error.

Could you please anyone help me to resolve tis issue

**Comment by joetrav** [comment]
Hello, thank you for the feedback.
We recently pushed a change that includes a tweak to how we're checking for a privileged user. 
 Would you mind pulling this latest change and let us know if addresses the issue you experienced when using Ansible?
If the behavior persists, please let us know, so that we can connect with you to collect more information to help diagnose the issue.

**Comment by Cappuccinuo** [comment]
This is a relative old issue.

If you can properly install the ansible package, on AL2, e.g. `sudo amazon-linux-extras install ansible2`.

And try with the following yaml file
```yaml
- name: Mount up efs
  hosts: localhost
  become_user: root

  tasks:
  - name: Mount
    mount:
        path: /mnt
        src: fs-12345678
        fstype: efs
        opts: tls
        state: mounted
```

And run with `sudo ansible-playbook test.yaml`
```bash
PLAY [Mount up efs] ****************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [localhost]

TASK [Mount] ***********************************************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

$ mount
127.0.0.1:/ on /mnt type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20282,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
```

It should not have any issue currently. Please feel free to reopen this issue if you still have problem.
